# Generated by Django 5.2.8 on 2025-12-25 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_bcnprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcnprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='bcnprofile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bcnprofile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcn_profiles', to='portal.club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
