# Generated by Django 5.2.8 on 2025-12-25 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_bcnprofile_full_name_bcnprofile_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcnprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bcnprofile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
