# Generated by Django 6.0 on 2025-12-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_bcnprofile_full_name_alter_bcnprofile_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='faculty',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Khoa / đơn vị'),
        ),
        migrations.AddField(
            model_name='club',
            name='field',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lĩnh vực'),
        ),
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Tạm dừng')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='bcnprofile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcn_members', to='portal.club'),
        ),
    ]
