# Generated by Django 6.0 on 2025-12-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_club_faculty_club_field_club_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='field',
            field=models.CharField(blank=True, choices=[('hoc-thuat', 'Học thuật, Chuyên môn'), ('nghe-thuat', 'Nghệ thuật, Sáng tạo'), ('truyen-thong', 'Truyền thông, Dịch vụ'), ('the-thao', 'Thể thao, Sức khoẻ'), ('so-thich', 'Sở thích, Giải trí'), ('tinh-nguyen', 'Tình nguyện, Cộng đồng'), ('ngon-ngu', 'Ngôn ngữ, Văn hoá'), ('esport', 'Thể thao, Điện tử')], max_length=150, null=True, verbose_name='Lĩnh vực'),
        ),
    ]
