# Generated by Django 6.0 on 2025-12-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_club_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email liên hệ'),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook/Website'),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='club',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Dán link ảnh (https://...). Nếu bỏ trống sẽ dùng ảnh mặc định.', null=True, verbose_name='Ảnh đại diện (URL)'),
        ),
        migrations.AddField(
            model_name='club',
            name='meeting_schedule',
            field=models.TextField(blank=True, help_text='VD: Thứ 7 hàng tuần 18:00 - 20:00 tại Phòng A1-203', null=True, verbose_name='Lịch sinh hoạt'),
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề sự kiện')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại sự kiện')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Ngày tổ chức')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ảnh sự kiện (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portal.club', verbose_name='CLB')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
