# Generated by Django 5.2.8 on 2026-01-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_club_contact_email_club_contact_facebook_and_more'),
        ('portal', '0007_event'),
    ]

    operations = [
    ]
