# Generated by Django 5.2.8 on 2026-01-03 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_merge_20260101_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
