# Generated by Django 6.0 on 2026-01-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Đã huỷ'),
        ),
    ]
