# Generated by Django 6.0 on 2026-01-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_clubevent_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Đã ẩn'),
        ),
    ]
